title: Heidelbergblick
title_separator: "|"
subtitle: Wohnanlagen Projekt
name: TH-Haus
description: Wohnanlagen Projekt
locale: de-DE

google_analytics:

#theme: minimal-mistakes-jekyll
remote_theme: iamsebastian/hbb-theme
plugins:
- jekyll-remote-theme
- jekyll-include-cache
#- github-pages

include: ["_pages"]

atom_feed:
  hide: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: false
      classes: wide
