title: Heidelbergblick
title_separator: "|"
subtitle: Wohnanlagen Projekt
name: TH-Holzbau-GmbH, Nordhausen
description: Wohnanlagen Projekt
locale: de-DE

remote_theme: iamsebastian/hbb-theme
plugins:
- jekyll-remote-theme
- jekyll-include-cache

include: ["_pages"]

atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: false
      classes: wide
